[Открыть в колабе](https://colab.research.google.com/github/maryszmary/DPO_2020/blob/master/3/linal_and_sklearn.ipynb)

# linear algebra with numpy

Это инструменты `numpy` Для линейной алгебры.

In [131]:
import numpy as np

## Матрицы

Создать матрицу можно так:

In [132]:
m = np.matrix([[1, 2], [3, 4]])

In [133]:
m

matrix([[1, 2],
        [3, 4]])

Или так:

In [134]:
arr = np.arange(10)
arr = arr.reshape(2, 5)
mat = np.matrix(arr)

In [135]:
mat

matrix([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [142]:
np.array(mat)[0]

array([0, 1, 2, 3, 4])

Тут у нас получилась прямоугольная матрица. С ней можно делать почти всё, что с квадратной.

### Умножение на число

In [143]:
m * 3

matrix([[ 3,  6],
        [ 9, 12]])

In [144]:
mat * 3

matrix([[ 0,  3,  6,  9, 12],
        [15, 18, 21, 24, 27]])

### Транспонирование

In [145]:
m

matrix([[1, 2],
        [3, 4]])

In [147]:
m.T

matrix([[1, 3],
        [2, 4]])

In [148]:
mat

matrix([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [149]:
mat.T

matrix([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])

### Сложение матриц

In [150]:
m2 = np.matrix([[10, 10], [10, 10]])
m2

matrix([[10, 10],
        [10, 10]])

In [151]:
m + m2

matrix([[11, 12],
        [13, 14]])

### Матричное умножение

In [36]:
m * m2

matrix([[30, 30],
        [70, 70]])

Заметьте, что это отличается от умножения векторов!

In [40]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 10, 10, 10])
a * b

array([10, 20, 30, 40])

Перемножение матриц разных размерностей:

In [37]:
m * mat

matrix([[10, 13, 16, 19, 22],
        [20, 27, 34, 41, 48]])

In [41]:
mat.T * mat

matrix([[25, 30, 35, 40, 45],
        [30, 37, 44, 51, 58],
        [35, 44, 53, 62, 71],
        [40, 51, 62, 73, 84],
        [45, 58, 71, 84, 97]])

In [42]:
mat * mat.T

matrix([[ 30,  80],
        [ 80, 255]])

А вот так не работает. Понимаете, почему?

In [38]:
mat * m

ValueError: shapes (2,5) and (2,2) not aligned: 5 (dim 1) != 2 (dim 0)

### Обратная матрица

In [53]:
inv_m = m ** -1

In [54]:
inv_m

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [55]:
inv_m * m

matrix([[1.00000000e+00, 0.00000000e+00],
        [1.11022302e-16, 1.00000000e+00]])

Если мы не артефакты приближения, это была бы единичная матрица.

In [58]:
np.round(inv_m * m)

matrix([[1., 0.],
        [0., 1.]])

А вот от прямоугольной матрицы взять обратную нельзя.

In [59]:
mat ** -1

ValueError: input must be a square array

# Классификация текстов

Сегодня мы будем делать бинарную классификацию текстов, используя логистичексую регрессию и мешок слов.

### Задача

Мы будем учить классификатор отличать тексты из учебников программирования от библейских текстов. 

### Данные

Скачайте данные по [ссылке](https://drive.google.com/file/d/10vgOvk10yMelNlFAOdGt3YZG0icqp2TI/view?usp=sharing).

In [29]:
import pandas as pd

Загрузим данные в датасет:

In [30]:
df = pd.read_csv('bible_vs_coding.csv')

In [34]:
# посмотрим на них
df.head(10)

labels                                          sentences
0  testament                  И к кому из святых обратишься ты?
1  testament  И Зелфа, служанка Лиина, [зачала и] родила Иак...
2  testament  И когда умрет какой-либо скот, который употреб...
3     coding  (Не забывайте, что два сигнала,\nSIGKILL и  SI...
4  testament  В седьмой день встали рано, при появлении зари...
5  testament  И воспылал гнев Господа на Израиля, и водил Он...
6  testament  И сошел на него Дух Господень, и веревки, бывш...
7  testament  2\n\nИ пришел Ангел Господень из Галгала в Бох...
8     coding  Инварианты циклов\nДля всех трех вариантов лин...
9     coding  Поскольку выполняемые операции выполняются от\...

1. я живу в москве
2. в москве много людей
3. в москве холодно, холодно

    в людей много москве холодно я
1.   1  0     0     1      0      1
2.   1  1     1     1      0      0
3.   1  0     0     1      2      0

In [33]:
print(df.sentences.iloc[8])

Инварианты циклов
Для всех трех вариантов линейного поиска легко увидеть, что каждый из них дает пра­
вильный ответ.


### Векторизация

In [35]:
from sklearn.feature_extraction.text import CountVectorizer

In [36]:
toy_vectorizer = CountVectorizer()

In [37]:
toy_vectorizer.fit(['мягкие, мягкие коты', 'коты бегают', 'бегают'])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [38]:
toy_vectorizer.vocabulary_

{'бегают': 0, 'коты': 1, 'мягкие': 2}

In [39]:
toy_vectors = toy_vectorizer.transform(['мягкие, мягкие коты', 'коты бегают', 'бегают'])

In [41]:
toy_vectors

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [42]:
toy_vectors.todense()

matrix([[0, 1, 2],
        [1, 1, 0],
        [1, 0, 0]])

In [43]:
test_vectors = toy_vectorizer.transform(['коты мурлыкают', 'коты мягкие', 'бегают'])
test_vectors.todense()

matrix([[0, 1, 0],
        [0, 1, 1],
        [1, 0, 0]])

In [45]:
df.sentences[12]

'И сказал Бог Аврааму: Сару, жену твою, не называй Сарою, но да будет имя ей: Сарра;\n\nЯ благословлю ее и дам тебе от нее сына; благословлю ее, и произойдут от нее народы, и цари народов произойдут от нее.'

In [46]:
vec = CountVectorizer()

In [47]:
bag_of_words = vec.fit_transform(df.sentences)

In [49]:
len(df.sentences)

24902

In [48]:
bag_of_words

<24902x44976 sparse matrix of type '<class 'numpy.int64'>'
	with 387538 stored elements in Compressed Sparse Row format>

In [50]:
print(df.sentences[3])

(Не забывайте, что два сигнала,
SIGKILL и  SIGSTOP, не могут игнорироваться.)


In [51]:
df.labels[3]

'coding'

In [52]:
d = bag_of_words[3]
d = d.todense()

In [54]:
d.nonzero()

(array([0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([ 3855,  3886, 11678, 13880, 15533, 20730, 22281, 36256, 44070]))

In [58]:
vec.vocabulary_
id2word = {ind: word for (word, ind) in vec.vocabulary_.items()}

In [61]:
id2word[3886]

'sigstop'

### Обучение

In [63]:
from sklearn.model_selection import train_test_split

In [129]:
train_test_split?

In [65]:
X_train, X_test, y_train, y_test = train_test_split(bag_of_words, df.labels)

In [69]:
from sklearn.linear_model import LogisticRegression

In [124]:
lr = LogisticRegression(random_state=42)

In [125]:
lr.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=42, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [126]:
my_text = vec.transform(['Господь, директория каталог сортировка', 'господь победи вирус'])
my_text

<2x44976 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [128]:
# lr.predict(my_text)

In [88]:
lr.predict_proba(my_text)

array([[0.42904981, 0.57095019],
       [0.12139787, 0.87860213]])

### Оценка

In [89]:
from sklearn.metrics import classification_report

In [90]:
predicted_labels = lr.predict(X_test)

In [91]:
predicted_labels

array(['testament', 'coding', 'coding', ..., 'coding', 'testament',
       'coding'], dtype=object)

In [93]:
print(classification_report(y_test, predicted_labels))

              precision    recall  f1-score   support

      coding       0.98      0.99      0.98      2926
   testament       0.99      0.98      0.99      3300

    accuracy                           0.98      6226
   macro avg       0.98      0.98      0.98      6226
weighted avg       0.98      0.98      0.98      6226



## Самостоятельная работа / домашнее задание (маленькое)

Повторить обучение классификатора на семинаре для другой задачи: определение спама. 

#### 1. Данные
Скачайте и загрузите в датафрейм данные про определение спама ([ссылка](https://raw.githubusercontent.com/mohitgupta-omg/Kaggle-SMS-Spam-Collection-Dataset-/master/spam.csv)).

In [94]:
!wget https://raw.githubusercontent.com/mohitgupta-omg/Kaggle-SMS-Spam-Collection-Dataset-/master/spam.csv

--2020-03-18 21:34:37--  https://raw.githubusercontent.com/mohitgupta-omg/Kaggle-SMS-Spam-Collection-Dataset-/master/spam.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.244.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.244.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 503663 (492K) [text/plain]
Saving to: ‘spam.csv’

spam.csv            100%[===================>] 491,86K  --.-KB/s    in 0,1s    

2020-03-18 21:34:37 (3,52 MB/s) - ‘spam.csv’ saved [503663/503663]



In [95]:
spam = pd.read_csv('spam.csv', encoding='cp1251')

In [98]:
spam.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [113]:
spam.v2[spam.v1 == 'spam']

2       Free entry in 2 a wkly comp to win FA Cup fina...
5       FreeMsg Hey there darling it's been 3 week's n...
8       WINNER!! As a valued network customer you have...
9       Had your mobile 11 months or more? U R entitle...
11      SIX chances to win CASH! From 100 to 20,000 po...
12      URGENT! You have won a 1 week FREE membership ...
15      XXXMobileMovieClub: To use your credit, click ...
19      England v Macedonia - dont miss the goals/team...
34      Thanks for your subscription to Ringtone UK yo...
42      07732584351 - Rodger Burns - MSG = We tried to...
54      SMS. ac Sptv: The New Jersey Devils and the De...
56      Congrats! 1 year special cinema pass for 2 is ...
65      As a valued customer, I am pleased to advise y...
67      Urgent UR awarded a complimentary trip to Euro...
68      Did you hear about the new \Divorce Barbie\"? ...
93      Please call our customer service representativ...
95      Your free ringtone is waiting to be collected....
113     GENT! 

#### 2. Мешок слов 
Получите вектора из текстов с помощью векторизатора.

In [102]:
vectorizer = CountVectorizer()

In [103]:
spam_vectors = vectorizer.fit_transform(spam.v2)

In [104]:
spam_vectors

<5572x8705 sparse matrix of type '<class 'numpy.int64'>'
	with 74012 stored elements in Compressed Sparse Row format>

#### 3. train_test_split

Разделите выборку на train и test.

In [105]:
X_train, X_test, y_train, y_test = train_test_split(spam_vectors, spam.v1)

#### 4. Обучение

In [106]:
lr = LogisticRegression()

In [107]:
lr.fit(X_train, y_train)

/home/maryszmary/.local/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

#### 5. Оценка

In [108]:
predicted = lr.predict(X_test)

In [110]:
print(classification_report(y_test, predicted))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      1188
        spam       0.99      0.87      0.92       205

    accuracy                           0.98      1393
   macro avg       0.98      0.93      0.96      1393
weighted avg       0.98      0.98      0.98      1393



In [120]:
vector = vectorizer.transform(['free urgent free jewellery free WINNER!!!'])

In [121]:
lr.predict(vector)

array(['ham'], dtype=object)